import { initialWorkplanValues, WorkplanValuesType } from "./workplanTypes"; 

// Fake Workplan 1
export const fakeWorkplans: WorkplanValuesType = {
  workplan: [
    {
            assignedWorker: { value: "worker1", label: "Worker One" },
            workerType: { value: "cleaner", label: "Cleaner" },
            setWorkDay: [],
            assignment: [
              {
                monthWeek: { value: "1", label: "1st week of month" },
                weekends: { value: "excWE", label: "Excl. weekends" },
                endDate: "2024-12-31",
                frequency: { value: "weekly", label: "Weekly" },
                interval: 1,
                isEndDate: false,
                months: [1, 2, 3, 4, 5, 6],
                isSeasonal: false,
                seasonal: {
                  monthWeek: { value: "1", label: "1st week of month" },
                  weekends: { value: "excWE", label: "Excl. weekends" },
                  frequency: { value: "weekly", label: "Weekly" },
                  interval: 1,
                  months: [1, 2, 3, 4, 5, 6],
                },
                separateStartDate: false,
                startDate: "2023-01-01",
                weekdays: [1, 3, 5],
                tasks: [
                  {
                    amount: 1,
                    duration: 30,
                    instruction: "Clean the lobby",
                    images: [],
                    notes: "Use eco-friendly products",
                    taskDescription: "Lobby cleaning",
                    taskValue: {label:"Lobby", value: "Lobby"},
                  },
                  {
                    amount: 2,
                    duration: 45,
                    instruction: "Vacuum all floors",
                    images: [],
                    notes: "Focus on high traffic areas",
                    taskDescription: "Floor vacuuming",
                    taskValue: {label:"Basement", value: "Lobby"},
                  },
                ],
              },
            ],
          },
          {
            assignedWorker: { value: "worker2", label: "Worker Two" },
            workerType: { value: "gardener", label: "Gardener" },
            setWorkDay: [2],
            assignment: [
              {
                monthWeek: { value: "1", label: "1st week of month" },
                weekends: { value: "excWE", label: "Excl. weekends" },
                endDate: "2024-12-31",
                frequency: { value: "weekly", label: "Weekly" },
                interval: 1,
                isEndDate: true,
                months: [1, 2, 3, 4, 5, 6],
                isSeasonal: false,
                seasonal: {
                  monthWeek: { value: "1", label: "1st week of month" },
                  weekends: { value: "excWE", label: "Excl. weekends" },
                  frequency: { value: "weekly", label: "Weekly" },
                  interval: 1,
                  months: [1, 2, 3, 4, 5, 6],
                },
                separateStartDate: false,
                startDate: "2023-01-01",
                weekdays: [1, 3, 5],
                tasks: [
                  {
                    amount: 1,
                    duration: 60,
                    instruction: "Trim the hedges",
                    images: [],
                    notes: "Ensure even trimming",
                    taskDescription: "Hedge trimming",
                    taskValue: {label:"HEdge", value: "Lobby"},
                  },
                  {
                    amount: 3,
                    duration: 90,
                    instruction: "Mow the lawn",
                    images: [],
                    notes: "Dispose of clippings",
                    taskDescription: "Lawn mowing",
                    taskValue: {label:"grass", value: "Lobby"},
                  },
                ],
              },
            ],
          },
          {
            assignedWorker: { value: "worker3", label: "Worker Three" },
            workerType: { value: "handyman", label: "Handyman" },
            setWorkDay: [3],
            assignment: [
              {
                monthWeek: { value: "1", label: "1st week of month" },
                weekends: { value: "excWE", label: "Excl. weekends" },
                endDate: "2024-12-31",
                frequency: { value: "weekly", label: "Weekly" },
                interval: 1,
                isEndDate: true,
                months: [1, 2, 3, 4, 5, 6],
                isSeasonal: false,
                seasonal: {
                  monthWeek: { value: "1", label: "1st week of month" },
                  weekends: { value: "excWE", label: "Excl. weekends" },
                  frequency: { value: "weekly", label: "Weekly" },
                  interval: 1,
                  months: [1, 2, 3, 4, 5, 6],
                },
                separateStartDate: false,
                startDate: "2023-01-01",
                weekdays: [1, 3, 5],
                tasks: [
                  {
                    amount: 1,
                    duration: 120,
                    instruction: "Fix any broken items in the building",
                    images: [],
                    notes: "Check all common areas",
                    taskDescription: "Building maintenance",
                    taskValue: {},
                  },
                  {
                    amount: 1,
                    duration: 30,
                    instruction: "Replace light bulbs",
                    images: [],
                    notes: "Use energy-efficient bulbs",
                    taskDescription: "Light bulb replacement",
                    taskValue: {},
                  },
                ],
              },
            ],
          },
        ],
      }